### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by daretmavi** [ThizThizzyDizzy/tree-feller#85]
Don't work with paper 1.20.4 server

I get this error in console:
```
[17:38:59 ERROR]: Could not pass event BlockBreakEvent to TreeFeller v1.22.2
java.lang.NoClassDefFoundError: Could not initialize class com.thizthizzydizzy.vanillify.Vanillify
        at com.thizthizzydizzy.treefeller.FellBehavior.processNaturalFallBehavior(FellBehavior.java:277) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.FellBehavior.processDelayedNaturalFallBehavior(FellBehavior.java:262) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.FellBehavior.access$200(FellBehavior.java:14) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.FellBehavior$13.breakBlock(FellBehavior.java:157) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:977) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:295) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:97) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:94) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:91) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:88) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.treefeller.TreeFellerEventListener.onBlockBreak(TreeFellerEventListener.java:26) ~[TreeFeller-1.22.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor138.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-422]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-422]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-422]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:298) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-422]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-422]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-422]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-422]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-422]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-422]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-422]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-422]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: [VANILLIFY] Unsupported server version: 1_20_R3 [in thread "Server thread"]
        at com.thizthizzydizzy.vanillify.version.VersionMatcher.lambda$match$1(VersionMatcher.java:46) ~[TreeFeller-1.22.2.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.thizthizzydizzy.vanillify.version.VersionMatcher.match(VersionMatcher.java:46) ~[TreeFeller-1.22.2.jar:?]
        at com.thizthizzydizzy.vanillify.Vanillify.<clinit>(Vanillify.java:7) ~[TreeFeller-1.22.2.jar:?]
        ... 38 more

```

**Comment by ThizThizzyDizzy** [comment]
Updated vanillify and released; fixed in v1.22.3
