### ISSUE TITLE
TreeFeller 1.26.1 doesn't work on Purpur 1.21.4

### ISSUE THREAD

**Issue by FaultyFunctions** [ThizThizzyDizzy/tree-feller#112]
I'm getting an error similar to #106 but downgrading to TreeFeller 1.25.1 fixes the issue.
```
[23:16:58] [Server thread/ERROR]: Could not pass event BlockBreakEvent to TreeFeller v1.26.1
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R4/entity/CraftEntity
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.vanillify.version.Wrapper1_21_R4.modifyEntityNBT(Wrapper1_21_R4.java:23) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.vanillify.Vanillify.modifyEntityNBT(Vanillify.java:12) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.FellBehavior.processFallBehavior(FellBehavior.java:237) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.FellBehavior.processDelayedFallBehavior(FellBehavior.java:210) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.FellBehavior.access$100(FellBehavior.java:14) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.FellBehavior$6.breakBlock(FellBehavior.java:87) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.breakBlock(TreeFeller.java:992) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:295) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:97) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:94) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:91) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.TreeFeller.fellTree(TreeFeller.java:88) ~[TreeFeller-1.26.1.jar:?]
	at TreeFeller-1.26.1.jar/com.thizthizzydizzy.treefeller.TreeFellerEventListener.onBlockBreak(TreeFellerEventListener.java:30) ~[TreeFeller-1.26.1.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:336) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:306) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:268) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1935) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:10) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1494) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1474) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1468) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1425) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1433) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313) ~[purpur-1.21.4.jar:1.21.4-2416-51aafbc]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R4.entity.CraftEntity
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 39 more
```

**Comment by ThizThizzyDizzy** [comment]
Unable to reproduce on latest Purpur 1.21.4
